In [1]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv(r"D:\Usuarios\wilmagju\OneDrive - Seguros Suramericana, S.A\Documents\GitHub\Repositorio-secreto-Scielo\Data\scopus_final.csv")
df.head(5)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Author(s)_ID_Rev,Title,Year,Source_title,Document_Type,Abstract,Authors_Rev,Total_Citation,Total_Title,...,C_10,C_11,C_13,C_12,C_14,C_15,C_16,C_17,C_18,C_19
0,0,57209325639,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Hassanzadeh-Taheri M.,0,1,...,8,1,0,8,6,9,6,0,0,8
1,1,57209308260,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Hassanzadeh-Taheri M.,0,1,...,8,1,0,8,6,9,6,0,0,8
2,2,57201482981,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Jahani F.,0,1,...,8,1,0,8,6,9,6,0,0,8
3,3,57209301343,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Erfanian Z.,0,1,...,8,1,0,8,6,9,6,0,0,8
4,4,26632069100,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Moodi H.,0,1,...,8,1,0,8,6,9,6,0,0,8

In [ ]:
#df.sort_values(by="Cited_by",ascending=False)   cuando necesite ordenar

In [6]:
df2 = df

In [39]:
# Se establecen las condiciones para la valoracion de los articulos mas populares y menos populares
condiciones = [
    (df2['Cited_by'] >= 200) ,
    (df2['Cited_by'] < 200) & (df2['Cited_by'] >= 100),
    (df2['Cited_by'] < 100) & (df2['Cited_by'] >= 50),
    (df2['Cited_by'] < 50) & (df2['Cited_by'] >= 10),
    (df2['Cited_by'] < 10) & (df2['Cited_by'] >= 5),
    (df2['Cited_by'] < 5) & (df2['Cited_by'] > 0),
     (df2['Cited_by'] == 0)
    
]
eleccion = ['1', '2', '3','4','5','6','7']
df2['nivel_de_citacion'] = np.select(condiciones, eleccion, default='error')
df2.head()

,Unnamed: 0,Author(s)_ID_Rev,Title,Year,Source_title,Document_Type,Abstract,Authors_Rev,Total_Citation,Total_Title,...,C_11,C_13,C_12,C_14,C_15,C_16,C_17,C_18,C_19,nivel_de_citacion
0,0,57209325639,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Hassanzadeh-Taheri M.,0,1,...,1,0,8,6,9,6,0,0,8,7
1,1,57209308260,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Hassanzadeh-Taheri M.,0,1,...,1,0,8,6,9,6,0,0,8,7
2,2,57201482981,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Jahani F.,0,1,...,1,0,8,6,9,6,0,0,8,7
3,3,57209301343,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Erfanian Z.,0,1,...,1,0,8,6,9,6,0,0,8,7
4,4,26632069100,The impact of long-term consumption of diets e...,2019,Anais da Academia Brasileira de Ciencias,Article,"To date, most of studies have only focused on ...",Moodi H.,0,1,...,1,0,8,6,9,6,0,0,8,7

In [40]:
# Revisar cuantos articulos tiene el nivel de popularidad

df2['nivel_de_citacion'].value_counts()

7    23862
6    19539
5     3708
4     1397
3       17
1        5
2        1
Name: nivel_de_citacion, dtype: int64

In [55]:
df2['Cited_by'].quantile([0.20, 0.75,  0.8,  0.95,0.97 ])

0.20    0.0
0.75    2.0
0.80    3.0
0.95    7.0
0.97    9.0
Name: Cited_by, dtype: float64

In [41]:
df2['Cited_by'].max()

221

In [42]:
df2.columns

Index(['Unnamed: 0', 'Author(s)_ID_Rev', 'Title', 'Year', 'Source_title',
       'Document_Type', 'Abstract', 'Authors_Rev', 'Total_Citation',
       'Total_Title', 'Max_Citation', 'Total_Journal', 'Delta_publications',
       'autor_career', 'citation_journal', 'Delta_coautores', 'Cited_by',
       'Years', 'cant_coautores', 'journal_mean_citation', 'index',
       'CiteScore', 'Percentile', 'Citation Count', 'Scholarly Output',
       'Percent Cited', 'SNIP', 'SJR', 'Scopus Sub-Subject Area', 'h-index',
       'Abstract_ing', 'Clean_Abstract', 'C_3', 'C_4', 'C_5', 'C_6', 'C_7',
       'C_8', 'C_9', 'C_10', 'C_11', 'C_13', 'C_12', 'C_14', 'C_15', 'C_16',
       'C_17', 'C_18', 'C_19', 'nivel_de_citacion'],
      dtype='object')

In [44]:
dataset = df2[['Year', 'Source_title',
       'Document_Type',  'Total_Citation',
       'Total_Title', 'Max_Citation', 'Total_Journal', 'Delta_publications',
       'autor_career', 'citation_journal', 'Delta_coautores', 
       'Years', 'cant_coautores', 'journal_mean_citation', 'index',
       'CiteScore', 'Percentile', 'Citation Count', 'Scholarly Output',
       'Percent Cited', 'Scopus Sub-Subject Area', 'h-index',
        'nivel_de_citacion']]

dataset.head(5)

,Year,Source_title,Document_Type,Total_Citation,Total_Title,Max_Citation,Total_Journal,Delta_publications,autor_career,citation_journal,...,journal_mean_citation,index,CiteScore,Percentile,Citation Count,Scholarly Output,Percent Cited,Scopus Sub-Subject Area,h-index,nivel_de_citacion
0,2019,Anais da Academia Brasileira de Ciencias,Article,0,1,0,1,1,0,9.146637,...,9.146637,0,1.19,79,778,654,55,Multidisciplinary,0.0,7
1,2019,Anais da Academia Brasileira de Ciencias,Article,0,1,0,1,1,0,9.146637,...,9.146637,0,1.19,79,778,654,55,Multidisciplinary,0.0,7
2,2019,Anais da Academia Brasileira de Ciencias,Article,0,1,0,1,1,0,9.146637,...,9.146637,0,1.19,79,778,654,55,Multidisciplinary,0.0,7
3,2019,Anais da Academia Brasileira de Ciencias,Article,0,1,0,1,1,0,9.146637,...,9.146637,0,1.19,79,778,654,55,Multidisciplinary,0.0,7
4,2019,Anais da Academia Brasileira de Ciencias,Article,0,1,0,1,1,0,9.146637,...,9.146637,0,1.19,79,778,654,55,Multidisciplinary,0.0,7

In [45]:

# Clasificacion de los parametros
X = dataset.iloc[:, [0,21]].values
y = dataset.iloc[:, 22].values

In [46]:
# Dividir el data set en conjunto de entrenamiento y conjunto de testing
from sklearn.model_selection import train_test_split # componente que nos permite hacer la particion
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [47]:
# Ajustar el clasificador de Árbol de Decisión en el Conjunto de Entrenamiento son varios clasificadores o modelos 
#entropy es uno
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = "entropy", random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [48]:
# Predicción de los resultados con el Conjunto de Testing
y_pred  = classifier.predict(X_test)

In [49]:
# Elaborar una matriz de confusión
from sklearn.metrics import confusion_matrix # Componente del paquete para esta funcionalidad
cm = confusion_matrix(y_test, y_pred)

In [50]:
cm

array([[   0,    0,    0,    0,    3,    0],
       [   0,    0,    0,    0,    3,    0],
       [   0,    0,    0,    0,  355,    0],
       [   0,    0,    0,    0,  894,    9],
       [   0,    0,    0,    0, 4730,  155],
       [   0,    0,    0,    0, 1429, 4555]], dtype=int64)

In [51]:
y_test

array(['6', '6', '7', ..., '7', '7', '7'], dtype=object)

In [52]:
y_pred

array(['6', '6', '6', ..., '7', '7', '7'], dtype=object)

In [53]:
from sklearn.metrics import accuracy_score # revisar el nivel de precicion
accuracy_score(y_test, y_pred)

0.7652682766010055